### PR TITLE
Add Events page and uuid for React list elements

### PR DESCRIPTION
**Pull request by nijek**
work in progress for issue #30 

## Changes proposed
Add Events header button to the Navbar
Add Events section to the Homepage 
Add padding to the bottom of the page's body
Add uuid library and provide unique keys for list elements in React 

## Screenshots
Navbar:
image
Events section on the homepage with events preview cards
image
image
Event card after clicking (the event card expands and show more information about the event)
image

## Note to reviewers:
I'd love to hear opinions and suggestions to improve. I wasn't able to figure out how to make smoother transitions from the preview cards to the expanded cards. I believe that adding some images to the Events and Jobs sections would be nice and consistent with the other sections.   

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. <br>
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). <br>
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by 0xk4b1r — CHANGES_REQUESTED** [review]
You have to fetch the new code into your repo and branch to resolve conflicts.

If you need any help letusknow

**Comment by nijek** [comment]
I decided to change a few other things, so I'm going to close this pr and open another one.

**Comment by 0xk4b1r** [comment]
> I decided to change a few other things, so I'm going to close this pr and open another one.

you don't have to close
if you push the code on the same branch. the code will reflect in this pr automatically

**Comment by nijek** [comment]
Thanks, @kabir0x23. I also wanted to change the screenshots and the PR description. I just finished creating the new PR.

**Comment by 0xk4b1r** [comment]
> 

and that you can edit pr from the top
but its okay now

**Comment by nijek** [comment]
Oh, I didn't know. Next time I'll do it like that. Thanks

**Pull request closed without merging**
