### PR TITLE
a page to show the open source projects

### LINKED ISSUE #33: [FEATURE] Create a page to showcase our open-source projects
### Detailed description

Create a page to showcase our open-source projects

open-source projects list:
https://github.com/CryptoverseWeb3

### Context
example: https://www.thecyberhub.org/projects
sourcecode: https://github.com/thecyberworld/thecyberhub.org

### Possible implementation

_No response_

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MISSIC17**
## Fixes Issue

Closes #33  

## Changes proposed

Adds Project element in the sidebar and navbar
Adds Projects component in the homepage.jsx
Adds routes for the invidual projects

## Screenshots

Screenshot from 2022-10-17 18-37-52
Screenshot from 2022-10-17 18-53-33

## Note to reviewers

It would be great to hear your comments on this pull request. I hope to improve myself through the comments. And, the sidebar seems to use styled.div instead of styled(LinkScroll). I didn't change it. Left it to your wisdom.

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. <br>
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). <br>
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by 0xk4b1r — APPROVED** [review]
Awesome 😄

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Comment by 0xk4b1r** [comment]
Can you fetch the new code into your repo, and in your branch?

**Review by 0xk4b1r — CHANGES_REQUESTED** [review]
You have to fetch the new code into your repo and branch to resolve conflicts.

If you need any help letusknow

**Comment by MISSIC17** [comment]
hey, I am having difficulty resolving the conflicts. It says my branch is 3 commits ahead and 2 commits behind, how do I fix this?

**Review by 0xk4b1r — APPROVED** [review]
Awesome 😄

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Pull request merged**
