### PR TITLE
[FEATURE] Join Button now link to discord community account

### LINKED ISSUE #18: [BUG] join button not linking to anywhere
### Detailed description

provide the discord link to join the community, once is been click direct user to discord account. 

### Context

-- it helps any user visiting the site to join the community
-- to get more information
-- create intro to web3

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ShorunTech**
Join Button Now Link to Discord Community.

## Fixes Issue

closes #18
## Changes proposed
-- On Click Join Button link to Discord Community 

## Code of Conduct
- [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. <br>
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). <br>
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ShorunTech** [comment]
Take a look at the changes made.

**Comment by ShorunTech** [comment]
Pls can any maintenance response to this changes, so I can proceed to the next one.

**Review by 0xk4b1r — APPROVED** [review]
Looks good

**Comment by 0xk4b1r** [comment]
Thanks for contributing to this project

**Review by 0xk4b1r — COMMENTED** [review]
Awesome 

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Pull request merged**
