### PR TITLE
Implement Jobs/Internship page and changes Info.jsx to allow display …

### PR DESCRIPTION
**Pull request by nijek**
…of information without button or image

Work in progress for Issue  #32 

## Changes proposed
Add Jobs header button to the Navbar.
Add Jobs page with job/internship offers inside cards.
In Info.jsx: buttonType=null creates Info element without a button, img=null creates Info element without image, this is useful to render an element without button or image. 

## Screenshot
image
image

## Note to reviewers:
I'd love to hear opinions and suggestions to improve. I believe that the "timeSincePosted" prop can be automatically calculated, but we would have to import Date libraries. 

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. <br>
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). <br>
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by 0xk4b1r** [comment]
Awesome @nijek 
Looking good 👍

**Comment by 0xk4b1r** [comment]
work in progress, 
completes, or still progress?
so I can merge it now.......................

**Review by 0xk4b1r — APPROVED** [review]
Awesome thanks for contributing to this project.

If you want to contribute more.

Make sure to check out out other repos

**Comment by nijek** [comment]
Completed, you can merge it now.

**Comment by 0xk4b1r** [comment]
> Completed, you can merge it now.

okay nice

**Pull request merged**
